[package]
name = "day8"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
regex = { workspace = true }
